# This is a basic workflow to help you get started with Actions

name: two jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Linux commands
        run: |
          cat README.md
          echo "Kernel version: $(uname -r)"


  job-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a simple script to check operation system!
        run: Get-CimInstance Win32_OperatingSystem
